export const actionTypes = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  CHANGE_STATUS: 'CHANGE_STATUS',
  REGISTER_FAILED: 'REGISTER_FAILED',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  NAME_CHAT_USER: 'NAME_CHAT_USER'
}
