export const config = {
   placeholderText: 'Edit Your Content Here!',
   charCounterCount: false,
   fontSize: false,
   fullScreen: false,
   strikeThrough: false,
   subscript: false,
   superscript: false,
   fontFamily: false,
   inlineClass: false,
   inlineStyle: false,
   paragraphStyle: false,
   lineHeight: false,
   paragraphFormat: false,
   align: false,
   outdent: false,
   indent: false,
   quote: false,
   formatOL: false,
   formatOLOptions: false,
   formatUL: false,
   formatULOptions: false,
   insertLink: false,
   insertImage: false,
   insertVideo: false,
   insertFile: false,
   insertTable: false,
   insertHR: false,
   print: false,
   getPDF: false,
   help: false,
   spellcheck: false,
}
